# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: shinybrar
          template: classic
          base: header, activity, community, repositories, metadata
          repositories: 200
          repositories_batch: 50
          repositories_forks: yes
          repositories_affiliations: ""
          config_timezone: America/Toronto
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: "C++"
          plugin_languages_limit: 10
          plugin_lines: yes
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]
          plugin_reactions_limit: 1000
          plugin_reactions_limit_issues: 1000
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 365
          plugin_habits_facts: yes
          plugin_habits_from: 10000
          plugin_habits_trim: yes
          plugin_contributors: yes
          plugin_contributors_base: ""
